import { useState } from "react";
import CountryCard from "./CountryCard";

const CountryFlag = (props) => {
    const [selectedCountry, setSelectedCountry] = useState(() => getRandomCountry(props.countriesList));
    
    const handleGenerateAgain = () => {
        setSelectedCountry(getRandomCountry(props.countriesList));
        const heading =document.getElementById('country_heading');
        heading.innerHTML ="Generated by clicking Button";
        heading.classList.remove('text-success');
        heading.classList.add('alert' ,'alert-info');
        heading.setAttribute('role', 'alert');
    };


    return (
        <div className="text-center">
            {/* <div className="col"> */}
            {/* </div> */}
            {/* <div className="col"> */}
                <div className="text-center text-success" id="country_heading">When Component is Mounted</div>
               <CountryCard flag={selectedCountry.flag} name={selectedCountry.name} capital={selectedCountry.capital} population={selectedCountry.population} currency={selectedCountry.currency} languages = {selectedCountry.languages} />
            {/* </div> */}
            <button className="btn btn-success mt-2" onClick={handleGenerateAgain}> Generate Again</button>
        </div>
    );

};

const getRandomCountry = (countriesList) => {
    let randomIndex =  Math.floor(Math.random()* countriesList.length);
    return countriesList[randomIndex];
}
export default CountryFlag;